funca?

diff --git a/.github/actions/coverage_and_test/action.yml b/.github/actions/coverage_and_test/action.yml
--- a/.github/actions/coverage_and_test/action.yml
+++ b/.github/actions/coverage_and_test/action.yml
@@ -7,38 +7,33 @@ runs:
     - name: "Run coverage"
       shell: bash
       run: |
+        set -euo pipefail
+
         PROJECT_PATH=$(pwd)
 
         ERROR_FILE_FLAG=$(pwd)/tests_errors.txt
-
-        CTEST_ERROR_FILE_FLAG=$(pwd)/ctest_errors.txt
         # run tests built with cmake
         # --output-on-faileure: prints everythin outputted by the tests if it fails
         # -VV verbose output
-        CTEST_COMMAND=$(ctest --test-dir build/hub/tests --output-on-failure -VV 2>> $CTEST_ERROR_FILE_FLAG 1>>$ERROR_FILE_FLAG)
-        CTEST_COMMAND=$(ctest --test-dir build/warehouse/tests --output-on-failure -VV 2>> $CTEST_ERROR_FILE_FLAG 1>>$ERROR_FILE_FLAG)
-        CTEST_COMMAND=$(ctest --test-dir build/server/tests --output-on-failure -VV 2>> $CTEST_ERROR_FILE_FLAG 1>>$ERROR_FILE_FLAG)
+        ctest --test-dir build/hub/tests --output-on-failure --no-tests=error -VV 2>&1 | tee -a "$ERROR_FILE_FLAG"
+        ctest --test-dir build/warehouse/tests --output-on-failure --no-tests=error -VV 2>&1 | tee -a "$ERROR_FILE_FLAG"
+        ctest --test-dir build/server/tests --output-on-failure --no-tests=error -VV 2>&1 | tee -a "$ERROR_FILE_FLAG"
 
-        if [ -s $CTEST_ERROR_FILE_FLAG ]; then
-          echo "Error: Unit Tests Failed"
-          exit 1
-        else
-          echo "All tests were passed!"
-        fi
+        echo "All tests were passed!"
 
         # run coverage of those tests and oputput to file
-        gcovr -r $PROJECT_PATH . >> $ERROR_FILE_FLAG
+        gcovr -r "$PROJECT_PATH" . >> "$ERROR_FILE_FLAG"
 
         echo "Runnig: gcovr -r $PROJECT_PATH ."
 
-        cat $ERROR_FILE_FLAG
+        cat "$ERROR_FILE_FLAG"
 
         # Find the value of correct coverage
         # parse coverage output file and extracts coverage percentage
         # grep pulls out the line of the total
         # awk prints only the last field (NF = number of fields of the grepped line)
         # cut finnaly creates a list using '%' as a delimiter (-d '%') and keeps first value (-f 1)
-        COVERAGE_RESULT=$(grep "TOTAL" $ERROR_FILE_FLAG | awk '{print $NF}' | cut -d '%' -f 1)
+        COVERAGE_RESULT=$(grep "TOTAL" "$ERROR_FILE_FLAG" | awk '{print $NF}' | cut -d '%' -f 1)
 
         # Coverage lines GT 80
         if [ "$(echo "$COVERAGE_RESULT > 80" | bc)" -eq 1 ]; then
